### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Ananthavijay** [Ananthavijay/Zero-to-Hero#1]
Add fancy badges

**Comment by kamontat** [comment]
I will get this

**Comment by Ananthavijay** [comment]
when u complete this don't forget to  add your name to contributors section in readme

**Comment by Ananthavijay** [comment]
@kamontat  It's all yours

**Comment by TheOrangePuff** [comment]
I just finished this 😢 My bad should have said before I started

**Comment by kamontat** [comment]
https://github.com/Ananthavijay/Zero-to-Hero/pull/5

**Comment by kamontat** [comment]
Since you don't have any code yet. so I will add the only Github relate badge.

**Comment by Ananthavijay** [comment]
@TheOrangePuff You could u also do Make a PR

**Comment by Ananthavijay** [comment]
Add some fancy badges like love,opensource etc..

**Comment by Ananthavijay** [comment]
Completed by @kamontat and @AllenAJ
