### ISSUE TITLE
Add installation guide 

### ISSUE THREAD

**Issue by Ananthavijay** [Ananthavijay/Zero-to-Hero#3]
Add installation guide of c++ for various OS

**Comment by Ananthavijay** [comment]
when u complete this don't forget to add your name to contributors section in readme

**Comment by salilbc** [comment]
Can I take this?

**Comment by Ananthavijay** [comment]
Yep @salilbc

**Comment by tushar231** [comment]
> Add installation guide of c++ for various OS

I'm interested in c++ installation in windows.
can I ??

**Comment by salilbc** [comment]
Raised PR

**Comment by Ananthavijay** [comment]
Completed by @salilbc
